Repository forHUFS/hufs-backend, pull requests merged in 2021-03, with the labels that each got.

#1 [ 김하연 ] 기능추가: 게시글 관련 기능
  .gitignore
  app.js
  controller/board.js
  controller/main.js
  controller/post.js
  controller/reply.js
  models/boards.js
  models/categories.js
  models/directories.js
  models/image.js
  models/index.js
  models/posts.js
  models/repiles.js
  models/reports.js
  models/scraps.js
  models/storeCategories.js
  models/storeReviews.js
  models/storeSubCategories.js
  models/stores.js
  package-lock.json
  package.json
  routes/board.js
  routes/main.js
  routes/post.js
  routes/reply.js
  server.js
  uploads/upload.js
Labels: Status: 리뷰 요청

#3 [ 이태현 ] 기능 추가: Swagger
  app.js
  package.json
  swagger/swagger.yaml
Labels: Status: 리뷰 요청

#5 [ 이태현 ] 기능 추가: Google / Kakao Social Login, JWT, Email Verification
  app.js
  controller/user.js
  middleware/auth.js
  models/index.js
  models/tokens.js
  models/users.js
  modules/auth.js
  modules/jwt.js
  package.json
  routes/post.js
  routes/user.js
  views/join.html
  views/test.html
Labels: Status: 리뷰 요청

#9 WIP
  controller/post.js
  controller/user.js
  middlewares/auth.js
  models/timeTables.js
  models/users.js
  modules/auth.js
  modules/jwt.js
  routes/post.js
  routes/user.js
  swagger/swagger.yaml
Labels: Status: Conflict 해결 요청

#10 [ 이태현 ] 기능 구현: 로그아웃 엔드포인트, 쿠키 / 세션 관련 리팩토링
  app.js
  controller/user.js
  middlewares/auth.js
  routes/user.js
  views/test.html
Labels: Status: Done

#11 [ 이태현 ] 기능 추가: User Report Count를 위한 Middleware 추가
  middlewares/reports.js
  routes/user.js
Labels: Status: Merge 요청, Status: 리뷰 요청

#13 [ 김하연 ] 기능추가: 신고 기능 및 상황별 이미지 삭제 기능 추가와 포스트-유저 연결
  .gitignore
  app.js
  controller/board.js
  controller/main.js
  controller/post.js
  controller/reply.js
  controller/user.js
  middlewares/auth.js
  models/creditScores.js
  models/directories.js
  models/image.js
  models/index.js
  models/likeRecord.js
  models/likeRecordOfPost.js
  models/likeRecordOfReply.js
  models/posts.js
  models/replies.js
  models/reportOfPost.js
  models/reportOfReply.js
  models/reviewImage.js
  models/scraps.js
  models/storeReviews.js
  models/storeSubCategories.js
  models/stores.js
  models/users.js
  routes/board.js
  routes/main.js
  routes/post.js
  routes/reply.js
  swagger/swagger.yaml
  uploads/upload.js
  views/join.html
  views/test.html
Labels: Status: 리뷰 요청

#14 [ 이태현 ] 기능 수정: 신고 및 정지 미들웨어 사용자 ID 받는 방식 및 response 수정
  middlewares/reports.js
Labels: Status: Merge 요청, Status: 리뷰 요청

#15 [ 이태현 ] 기능 추가: 스크랩 디렉토리 & 게시글 스크랩 엔드 포인트 추가 및 리팩토링 & Swagger 작성
  controller/user.js
  models/directories.js
  routes/user.js
  swagger/swagger.yaml
  views/test.html
Labels: Status: Merge 요청, Status: 리뷰 요청

#16 [ 김하연 ] 기능추가: 상점 리뷰 CRUD 기능 추가, 응답 형태 리팩토링, 스웨거 작성
  app.js
  controller/board.js
  controller/main.js
  controller/post.js
  controller/reply.js
  controller/store.js
  controller/user.js
  middlewares/reports.js
  models/reviewImage.js
  models/storeReviews.js
  routes/post.js
  routes/store.js
  swagger/swagger.yaml
  uploads/upload.js
Labels: Status: Done

#17 [ 김하연 ] 리팩토링: status code 리팩토링과 스웨거 수정
  app.js
  controller/board.js
  controller/post.js
  controller/reply.js
  controller/store.js
  swagger/swagger.yaml
Labels: Status: Done

#19 [ 김하연 ] 기능수정: 상점 리뷰 기능 수정 및 스웨거 수정
  app.js
  swagger/swagger.yaml
Labels: Status: Done

#20 [ 김하연 ] 기능수정: 상점 리뷰 기능 수정 및 스웨거 수정
  controller/main.js
  controller/store.js
  models/index.js
  models/reviewImage.js
  models/storeReviews.js
  routes/store.js
  swagger/swagger.yaml
Labels: Status: Done

#18 [ 이태현 ] 기능 수정: 게시글 스크랩, 디렉토리 관련 isAuthorized 추가 및 Error Handling과 Swagger 수정
  controller/user.js
  middlewares/auth.js
  routes/user.js
  swagger/swagger.yaml
Labels: Status: Merge 요청, Status: 리뷰 요청

#25 [ 이태현 ] 기능 추가: 주전공, 이중전공 관련 모델 및 엔드포인트 추가
  app.js
  controller/major.js
  models/doubleMajors.js
  models/index.js
  models/mainMajors.js
  models/tokens.js
  models/users.js
  routes/major.js
Labels: Status: Done

#26 [ 이태현 ] 기능 수정: Email 인증, 회원 가입, 회원 정보 기능 수정
  controller/user.js
  models/mainMajors.js
  models/tokens.js
Labels: Status: Done

#23 [ 김하연 ] 기능수정: 상태 코드 및 메시지 수정, 스웨거 수정
  .gitignore
  controller/board.js
  controller/main.js
  controller/post.js
  controller/reply.js
  controller/store.js
  models/stores.js
  routes/store.js
  swagger/swagger.yaml
Labels: Status: Done

#24 [ 이태현 ] 기능 추가: 장학금 정보 관련 모델 및 GET 엔드포인트 추가
  app.js
  controller/scholarship.js
  controller/user.js
  models/index.js
  routes/scholarship.js
  routes/user.js
  swagger/swagger.yaml
Labels: Status: Done

#27 [ 김하연 ] 기능삭제: 수정 중 작성 취소 기능 삭제(중복 삭제)
  controller/post.js
  routes/post.js
  swagger/swagger.yaml
Labels: Status: Merge 요청

#28 [ 김하연 ] 기타: Swagger 수정
  routes/store.js
  swagger/swagger.yaml
Labels: Status: Done
